site_name: Scaledown

theme:
  name: material
  logo: assets/highres_logo.png
  features:
    - navigation.tabs
    - content.tabs.link


nav:
  - 'Home': index.md
  - 'Getting Started':
    - getting_started/installation.md
    - 'User Guide':
      - getting_started/User Guide.md
      - getting_started/pruning.md
      - getting_started/knowledgedistillation.md
    - 'Docs':
      - api/index.md
      - 'Quantization':
        - api/weight_quantization.md
      - 'Knowledge Distilling':
        - api/knowledge_distillation.md
      - 'Pruning':
        - api/magnitude_pruning.md
  - 'Blog': https://scaledown-team.github.io/blog
  - 'Library': 
    - 'Hardware Library':
      - hardware_library/intro.md
      - hardware_library/hardwarepresent.md
      - hardware_library/requestforhardware.md
    - learn.md
  - 'Team':
    - 'Scaledown Team': team/team.md
extra:
  analytics:
    provider: google
    property: G-ELFBGLJEG4

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 
  - attr_list
  - md_in_html
