site_name: Scaledown

theme:
  name: material
  features:
    - navigation.tabs

nav:
  - 'Home': index.md
  - 'Getting Started':
    - getting_started/installation.md
  - 'User Guide':
    - guide/index.md
    - guide/quantization.md
    - guide/knowledgedistillation.md
    - guide/pruning.md
  - 'Docs':
    - api/index.md
    - 'Quantizing Models':
      - api/weight_quantization.md
  - 'Blog': https://scaledown-team.github.io/blog
  - 'Learn TinyML': https://scaledown-team.github.io/practical_tinyml_book/intro.html

extra:
  analytics:
    provider: google
    property: G-ELFBGLJEG4
