site_name: Scaledown

theme:
  name: material
  logo: assets/highres_logo.png
  features:
    - navigation.tabs

nav:
  - 'Home': index.md
  - 'Getting Started':
    - getting_started/installation.md
  - 'User Guide':
    - guide/index.md
    - guide/quantization.md
    - guide/knowledgedistillation.md
    - guide/pruning.md
  - 'Docs':
    - api/index.md
    - 'Quantization':
      - api/weight_quantization.md
    - 'Knowledge Distilling':
      - api/knowledge_distillation.md
    - 'Pruning':
      - api/magnitude_pruning.md
  - 'Blog': https://scaledown-team.github.io/blog
  - 'Learn TinyML': learn.md

extra:
  analytics:
    provider: google
    property: G-ELFBGLJEG4
