site_name: Scaledown

theme:
  name: material
  logo: assets/highres_logo.png
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.indexes
    - content.tabs.link

markdown_extensions:
  - pymdownx.inlinehilite
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 
  - attr_list
  - md_in_html

nav:
  - 'Home': index.md
  - 'Getting Started':
    - getting_started/installation.md
    - 'User Guide':
      - getting_started/User Guide.md
      - getting_started/pruning.md
      - getting_started/knowledgedistillation.md
  - 'Docs':
    - api/index.md
    - 'Quantization':
      - api/weight_quantization.md
    - 'Knowledge Distilling':
      - api/knowledge_distillation.md
  - 'Blog': https://scaledown-team.github.io/blog
  - 'Library': 
    - 'Hardware Library':
      - hardware_library/intro.md
      - hardware_library/hardwarepresent.md
      - hardware_library/requestforhardware.md
      - hardware_library/donatetous.md
    - learn.md
  - 'Team':
    - 'Scaledown Team': team/team.md
  - 'Conferences':
    - conferences/tinymlsummit.md
    - conferences/fossasia.md

extra_css:
  - stylesheets/extra.css

extra:
  analytics:
    provider: google
    property: G-ELFBGLJEG4
    
extra:
  social:
    - icon: fontawesome/brands/twitter 
      link: https://twitter.com/scaledown_team
      name: Scaledown Twitter

    - icon: fontawesome/solid/paper-plane
      link: mailto:scaledown.tinyml@gmail.com
      name: Reach out via email

    - icon: fontawesome/brands/github
      link: https://github.com/scaledown-team/
      name: Scaledown Github

    - icon: fontawesome/brands/slack
      link: https://join.slack.com/t/scaledownworkspace/shared_invite/zt-10s5tnxit-b8Xwf81zn4fMNSp9IiA_vA
      name: Scaledown Slack

    - icon: fontawesome/solid/hand-holding-dollar
      link: https://scaledown-team.github.io/hardware_library/donatetous/
      name: Donate



  extra:
  generator: false

