site_name: Scaledown

theme:
  name: material
  features:
    - navigation.tabs

nav:
  - 'Home': index.md
  - 'Getting Started':
    - getting_started/installation.md
  - 'API Reference':
    - api/index.md
  - 'Learn TinyML': https://scaledown-team.github.io/practical_tinyml_book/intro.html

extra:
  analytics:
    provider: google
    property: G-ELFBGLJEG4
